name: "hola mey"
on:
  push:
    branches: ["main"]
jobs: 
  deploy-meylin:
    runs-on: ubuntu-latest
    steps:
      run: echo "hacemos pull del codigo"
      run: echo "correr migraciones"
      run: echo "generar binario"
      run: echo "publicar version"